services:
  db:
    container_name: db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  search:
    build: ./search
    restart: always
    expose:
      - 3000
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices
  books:
    build: ./books
    restart: always
    expose:
      - 3000
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices
  videos:
    build: ./videos
    restart: always
    ports:
      - 3000
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices
  nginx:
    build: ./nginx
    ports:
      - '8080:80'
    depends_on:
      - books
      - search
      - videos
